export const countries = [
  {
    name: "Nigeria",
    capital: "Abuja",
    region: "Africa",
    population: 206139587,
    flag: "https://flagcdn.com/ng.svg",
  },
  {
    name: "United States of America",
    capital: "Washington, D.C.",
    region: "Americas",
    population: 329484123,
    flag: "https://flagcdn.com/us.svg",
  },
  {
    name: "Russian Federation",
    capital: "Moscow",
    region: "Europe",
    population: 144104080,
    flag: "https://flagcdn.com/ru.svg",
  },
];

export const country = {
  name: "Nigeria",
  topLevelDomain: [".ng"],
  alpha2Code: "NG",
  alpha3Code: "NGA",
  callingCodes: ["234"],
  capital: "Abuja",
  altSpellings: ["NG", "Nijeriya", "Naíjíríà", "Federal Republic of Nigeria"],
  subregion: "Western Africa",
  region: "Africa",
  population: 206139587,
  latlng: [10.0, 8.0],
  demonym: "Nigerian",
  area: 923768.0,
  gini: 35.1,
  timezones: ["UTC+01:00"],
  borders: ["BEN", "CMR", "TCD", "NER"],
  nativeName: "Nigeria",
  numericCode: "566",
  flags: {
    svg: "https://flagcdn.com/ng.svg",
    png: "https://flagcdn.com/w320/ng.png",
  },
  currencies: [
    {
      code: "NGN",
      name: "Nigerian naira",
      symbol: "₦",
    },
  ],
  languages: [
    {
      iso639_1: "en",
      iso639_2: "eng",
      name: "English",
      nativeName: "English",
    },
  ],
  translations: {
    br: "Nigéria",
    pt: "Nigéria",
    nl: "Nigeria",
    hr: "Nigerija",
    fa: "نیجریه",
    de: "Nigeria",
    es: "Nigeria",
    fr: "Nigéria",
    ja: "ナイジェリア",
    it: "Nigeria",
    hu: "Nigéria",
  },
  flag: "https://flagcdn.com/ng.svg",
  regionalBlocs: [
    {
      acronym: "AU",
      name: "African Union",
      otherNames: [
        "الاتحاد الأفريقي",
        "Union africaine",
        "União Africana",
        "Unión Africana",
        "Umoja wa Afrika",
      ],
    },
  ],
  cioc: "NGR",
  independent: true,
};
